/**
 * Generates `src/data/legacy-redirects.ts` — a map from the pre-migration PHP
 * site's `/index.php?article=<id>` URLs to the current article paths.
 *
 * Background: al-ibadah.com served articles at `/index.php?article=<id>` for ~20
 * years. The Astro rebuild changed every URL with no redirects in place, so that
 * entire (indexed, back-linked) URL space dead-ended and the site lost its search
 * rankings. The migration kept each article's old id in frontmatter as
 * `original_id`, which lets us rebuild a 1:1 301 map. Consumed by
 * `functions/_middleware.ts`.
 *
 * The new URL mirrors the content path exactly: the content-collection id is the
 * path under `content/` minus `.md` (see `src/pages/[category]/[slug].astro` and
 * `.../[subcategory]/[slug].astro`), and the canonical URL adds a trailing slash.
 *
 * Run: `pnpm generate:redirects` (also runs as the first step of `pnpm build`).
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import matter from 'gray-matter'

const CONTENT_DIR = 'content'
// The eight categories the content collection loads (see src/content.config.ts).
const CATEGORIES = [
  'troslara',
  'renhet',
  'bon',
  'allmosa',
  'fasta',
  'vallfard',
  'blandat',
  'biografier',
]
const OUT_FILE = 'src/data/legacy-redirects.ts'

/** All `.md` files under `dir`, excluding `_`-prefixed files (e.g. `_index.md`). */
function findMarkdown(dir: string): string[] {
  const out: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      out.push(...findMarkdown(full))
    } else if (!entry.name.startsWith('_') && entry.name.endsWith('.md')) {
      out.push(full)
    }
  }
  return out
}

const map = new Map<number, string>()
const collisions: string[] = []
let scanned = 0
let withoutId = 0
let skippedDepth = 0

for (const category of CATEGORIES) {
  for (const file of findMarkdown(join(CONTENT_DIR, category))) {
    scanned++
    const relNoExt = file.slice(CONTENT_DIR.length + 1).replace(/\.md$/, '')

    // Only 2-segment (/cat/slug) and 3-segment (/cat/sub/slug) ids have a route;
    // anything deeper has no built page, so a redirect there would 404.
    if (relNoExt.split('/').length > 3) {
      skippedDepth++
      console.warn(`  skipped (no route, too deep): ${file}`)
      continue
    }

    const { data } = matter(readFileSync(file, 'utf8'))
    const id = data.original_id
    if (typeof id !== 'number') {
      withoutId++
      continue
    }

    const path = `/${relNoExt}/`
    const existing = map.get(id)
    if (existing && existing !== path) collisions.push(`#${id}: ${existing} vs ${path}`)
    map.set(id, path)
  }
}

if (collisions.length > 0) {
  console.error(`\n✖ ${collisions.length} original_id collision(s) — refusing to generate:`)
  for (const c of collisions) console.error(`  ${c}`)
  process.exit(1)
}

const sorted = [...map.entries()].sort((a, b) => a[0] - b[0])
// Paths are URL-safe slugs (lowercase letters, digits, hyphens, slashes) with no
// quotes, so single-quoting them is safe and matches the project's Biome style.
const entries = sorted.map(([id, path]) => `  '${id}': '${path}',`).join('\n')

const output = `// AUTO-GENERATED by scripts/generate-legacy-redirects.ts — do not edit by hand.
// Maps the pre-migration PHP site's /index.php?article=<id> URLs to current paths.
// Regenerate with: pnpm generate:redirects
export const legacyRedirects: Record<string, string> = {
${entries}
}
`

writeFileSync(OUT_FILE, output)
console.log(
  `✓ ${OUT_FILE}: ${sorted.length} redirects ` +
    `(${scanned} scanned, ${withoutId} without original_id, ${skippedDepth} skipped)`
)
