/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermerRouteImport } from './routes/termer'
import { Route as OmRouteImport } from './routes/om'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryIndexRouteImport } from './routes/$category.index'
import { Route as CategorySubcategoryRouteImport } from './routes/$category.$subcategory'
import { Route as CategorySlugRouteImport } from './routes/$category.$slug'
import { Route as CategorySubcategoryIndexRouteImport } from './routes/$category.$subcategory.index'
import { Route as CategorySubcategorySlugRouteImport } from './routes/$category.$subcategory.$slug'

const TermerRoute = TermerRouteImport.update({
  id: '/termer',
  path: '/termer',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoryRoute,
} as any)
const CategorySubcategoryRoute = CategorySubcategoryRouteImport.update({
  id: '/$subcategory',
  path: '/$subcategory',
  getParentRoute: () => CategoryRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoryRoute,
} as any)
const CategorySubcategoryIndexRoute =
  CategorySubcategoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CategorySubcategoryRoute,
  } as any)
const CategorySubcategorySlugRoute = CategorySubcategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategorySubcategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/om': typeof OmRoute
  '/termer': typeof TermerRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/$category/$subcategory': typeof CategorySubcategoryRouteWithChildren
  '/$category/': typeof CategoryIndexRoute
  '/$category/$subcategory/$slug': typeof CategorySubcategorySlugRoute
  '/$category/$subcategory/': typeof CategorySubcategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/om': typeof OmRoute
  '/termer': typeof TermerRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/$category': typeof CategoryIndexRoute
  '/$category/$subcategory/$slug': typeof CategorySubcategorySlugRoute
  '/$category/$subcategory': typeof CategorySubcategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/om': typeof OmRoute
  '/termer': typeof TermerRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/$category/$subcategory': typeof CategorySubcategoryRouteWithChildren
  '/$category/': typeof CategoryIndexRoute
  '/$category/$subcategory/$slug': typeof CategorySubcategorySlugRoute
  '/$category/$subcategory/': typeof CategorySubcategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$category'
    | '/om'
    | '/termer'
    | '/$category/$slug'
    | '/$category/$subcategory'
    | '/$category/'
    | '/$category/$subcategory/$slug'
    | '/$category/$subcategory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/om'
    | '/termer'
    | '/$category/$slug'
    | '/$category'
    | '/$category/$subcategory/$slug'
    | '/$category/$subcategory'
  id:
    | '__root__'
    | '/'
    | '/$category'
    | '/om'
    | '/termer'
    | '/$category/$slug'
    | '/$category/$subcategory'
    | '/$category/'
    | '/$category/$subcategory/$slug'
    | '/$category/$subcategory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRouteWithChildren
  OmRoute: typeof OmRoute
  TermerRoute: typeof TermerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termer': {
      id: '/termer'
      path: '/termer'
      fullPath: '/termer'
      preLoaderRoute: typeof TermerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/': {
      id: '/$category/'
      path: '/'
      fullPath: '/$category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/$category/$subcategory': {
      id: '/$category/$subcategory'
      path: '/$subcategory'
      fullPath: '/$category/$subcategory'
      preLoaderRoute: typeof CategorySubcategoryRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/$category/$slug': {
      id: '/$category/$slug'
      path: '/$slug'
      fullPath: '/$category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/$category/$subcategory/': {
      id: '/$category/$subcategory/'
      path: '/'
      fullPath: '/$category/$subcategory/'
      preLoaderRoute: typeof CategorySubcategoryIndexRouteImport
      parentRoute: typeof CategorySubcategoryRoute
    }
    '/$category/$subcategory/$slug': {
      id: '/$category/$subcategory/$slug'
      path: '/$slug'
      fullPath: '/$category/$subcategory/$slug'
      preLoaderRoute: typeof CategorySubcategorySlugRouteImport
      parentRoute: typeof CategorySubcategoryRoute
    }
  }
}

interface CategorySubcategoryRouteChildren {
  CategorySubcategorySlugRoute: typeof CategorySubcategorySlugRoute
  CategorySubcategoryIndexRoute: typeof CategorySubcategoryIndexRoute
}

const CategorySubcategoryRouteChildren: CategorySubcategoryRouteChildren = {
  CategorySubcategorySlugRoute: CategorySubcategorySlugRoute,
  CategorySubcategoryIndexRoute: CategorySubcategoryIndexRoute,
}

const CategorySubcategoryRouteWithChildren =
  CategorySubcategoryRoute._addFileChildren(CategorySubcategoryRouteChildren)

interface CategoryRouteChildren {
  CategorySlugRoute: typeof CategorySlugRoute
  CategorySubcategoryRoute: typeof CategorySubcategoryRouteWithChildren
  CategoryIndexRoute: typeof CategoryIndexRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategorySlugRoute: CategorySlugRoute,
  CategorySubcategoryRoute: CategorySubcategoryRouteWithChildren,
  CategoryIndexRoute: CategoryIndexRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRouteWithChildren,
  OmRoute: OmRoute,
  TermerRoute: TermerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
